### ISSUE TITLE
mtk devices: tibu backup halts

### ISSUE THREAD

**Issue by tukusejssirs** [IzzySoft/Adebar#10]
I used this ![config](https://cloud.githubusercontent.com/assets/5111894/10426737/34ac46ac-70e3-11e5-8cf9-80e1f75e7427.jpg) file to generate backup. However, the output hangs on the following line:
`build.prop: 110 KB/s (4571 bytes in 0.040s)`
I check that `build.prop` is pulled, `wpa_supplicant.conf` just touched (empty file was created), and no `hosts` pulled.

This is the first time I tried to backup with tibu option enable, actually with all of the following settings enabled:

``` bash
# create the script to pull stuff from the TiBu web server
MK_TIBU=1
# process package information via dumpsys and generate userApps.md/sysApps.md
MK_USERAPPS=1
MK_SYSAPPS=1
MK_SYSAPPS_RETRIEVE_NAMES=1
# deal with the default-install-location (where apps should be installed)
MK_INSTALLLOC=1
```

I tried it using `master` and `devel` branch, too.

**Comment by IzzySoft** [comment]
TiBu has nothing to do with that. According to your description, the process is stuck in `pull_config.lib` shortly after line 25. What is your setting for `ROOT_COMPAT`? Depending on that, can you try the corresponding command manually:

```
# ROOT_COMPAT=1:
adb shell "su -c 'cat /data/misc/wifi/wpa_supplicant.conf'" > "wpa_supplicant.conf"
# ROOT_COMPAT=0:
adb pull /data/misc/wifi/wpa_supplicant.conf wpa_supplicant.conf
```

Then let me know which variant you used, and what happened (incl. messages shown).

**Comment by tukusejssirs** [comment]
`ROOT_COMPAT` is enabled. Btw, what’s the difference between the two commands? Is the one using `shell` faster? (I _do_ understand those commands on their own.)

**Comment by tukusejssirs** [comment]
Well, actually now it works with the same `config` file. It was probably just the data/system on the device which were somehow corrupted. Meanwhile I restored a twrp backup that I made earlier and the TiBu backup works. I just need to check if does restore the data or not.

**Comment by IzzySoft** [comment]
> what’s the difference between the two commands?

`adb pull` can directly access the file – but that only works if the ADB daemon on the device runs in root mode (aka "insecure mode"). If that's not the case, we need a work-around – as there's no combination of `su` and `adb pull` possible. Hence the `adb shell` trick, which I personally find a little "unclean" – but better that than nothing, right?

> actually now it works

Congrats! So shall I close this issue?

**Comment by tukusejssirs** [comment]
Thank you for the explanation. And go ahead and close it. ;)

**Comment by IzzySoft** [comment]
You're welcome as usual :)
