### ISSUE TITLE
TiBu: sms/call/bookmarks backup

### ISSUE THREAD

**Issue by tukusejssirs** [IzzySoft/Adebar#11]

**Comment by tukusejssirs** [comment]
I just found that TiBu can make a backup of sms/mms messages, call log and bookmarks of the stock browser — [here](http://forum.xda-developers.com/showthread.php?t=1754820)'s the link ([post #5](http://forum.xda-developers.com/showpost.php?p=28386115&postcount=5)). Probably you already know about this.

I noticed in one of `adebar` files you either want to or at least think about implementing this feature into `adebar`. It would great, I think. :)

**Comment by IzzySoft** [comment]
Yeah, would be great – if it were possible. Unfortunately, I couldn't find a way to achieve this – see [Backup/Restore SMS/MMS via ADB on a non-rooted device?](http://android.stackexchange.com/q/114437/16575)

So as much as I would like to do this (and I really do), unless there's a way to achieve it I can't. If you know any, be welcome to reopen this issue.

**Comment by tukusejssirs** [comment]
Okay, I see. But what about rooted devices? Would it be wise to include these backups _if_ the device is rooted?

**Comment by IzzySoft** [comment]
Same answer, I'm afraid. Rooted device isn't enough to give `adb backup` permission to the corresponding databases/providers – so we's need either a specific app on the device to care for some kind of export, or pull the database and take care for that ourselves. I wanted to avoid the former (_Adebar_ should not depend on specific apps being installed). If someone comes up with a solution to do that locally, it might be an option (and the original idea why I played with [ANDROID-SMS](https://github.com/IzzySoft/ANDROID-SMS)). So far, no suitable solution found.
