### ISSUE TITLE
adebar help

### ISSUE THREAD

**Issue by tukusejssirs** [IzzySoft/Adebar#2]
While there is no real need of `--help` parameter as there are literally no command-line parameters (which would be, perhaps good to introduce somewhere in future), a simple (maybe a bit more elaborate then the one already included when it is not run with proper syntax) help text is always good to have displayed (at least for newbies just like myself xD).

I created one, but it could be even better if it could include some more info about config file.

Here’s my piece of code (you could also include instances of bad syntax too display this help):

```
if [[ $1 = "--help" || $1 = "-h" ]]; then
    echo "Usage: ./adebar-cli <config|target_directory> [suffix]"
    echo "Android Device Backup and Report"
    echo
    echo "  -h, --help display this help and exit"
    echo
    echo "There are no other command-line parameters, because everything is done via config file."
    echo "You can get more information about configuration and usage of adebar"
    echo "on its github wiki <https://github.com/IzzySoft/Adebar/wiki>."
fi
```

**Comment by IzzySoft** [comment]
There you go :) More will come later, in case another CLI param is added. Thanks for bringing this up!

(checked into devel for now, will make it to master later when we've solved the other issue)
