### ISSUE TITLE
backup files are zero byte big

### ISSUE THREAD

**Issue by Micha-Btz** [IzzySoft/Adebar#22]
Hi there,
today i give adebar a try but it seems I have done things not right.
I just created a folder and let adebar run. the created script looks good, just wpa_supplicant.conf was not fetched.
i run a Sony Xperia Z1C Compact with cm-12.1 without gapps. 

[deviceInfo.md.zip](https://github.com/IzzySoft/Adebar/files/672908/deviceInfo.md.zip)
the deviceIfo file is the orginal just Sync provider details i have removed.

`~/handy/build/Adebar/z1c $ ./sysbackup 
backing up: com.android.providers.telephony
Now unlock your device and confirm the backup operation...
`

for each attempt to backup an app i get a confirmation dialogue on the phone (which drives me crazy, can i give the permission one for all?) but all backed up files are zero bites big.
![screenshot_2016-12-26-11-47-07](https://cloud.githubusercontent.com/assets/4420944/21481364/0bf7637e-cb67-11e6-8ede-99463cf77055.png)
~/handy/build/Adebar/z1c/userApps $ ll
insgesamt 0
drwxr-xr-x 1 mdomann mdomann 2,3K Dez 26 11:41 .
drwxr-xr-x 1 mdomann mdomann  218 Dez 26 11:44 ..
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:40 acr.browser.lightning.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:40 at.bitfire.davdroid.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:41 com.android.keepass.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:39 com.artifex.mupdfdemo.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:40 com.cliffcawley.calendarnotify.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:39 com.duolingo.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:39 com.eclipsim.gpsstatus2.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:40 com.fsck.k9.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:39 com.garzotto.iforest.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:39 com.google.zxing.client.android.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:39 com.hillman.out_loud.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:39 com.kebab.Llama.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:39 com.mapswithme.maps.pro.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:39 com.miadzin.shelves.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:40 com.miadzin.shelves.unlocker.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:36 com.nextcloud.client.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:41 com.nolanlawson.logcat.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:39 com.oleksiykovtun.picsontumblr.android.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:40 com.orux.oruxmaps.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:39 com.rerware.android.MyBackupPro.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:41 com.simplemobiletools.gallery.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:37 com.speedsoftware.rootexplorer.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:39 com.zoffcc.applications.zanavi.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:40 csd.qtproject.minesweeper.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:40 cz.eutopia.snooperstopper.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:40 de.baumann.thema.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:41 de.christinecoenen.code.zapp.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:40 de.easygo.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:36 de.hoffmannsgimmicks.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:40 de.reimardoeffinger.quickdic.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:39 dev.ukanth.ufirewall.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:40 de.yellowmap.cashpool.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:40 dk.tacit.android.foldersync.lite.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:41 doppelkopf.am.stammtisch.free.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:39 me.kuehle.carreport.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:37 net.reichholf.dreamdroid.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:39 org.connectbot.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:40 org.dmfs.tasks.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:40 org.fdroid.fdroid.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:41 org.horaapps.leafpic.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:39 org.nick.cryptfs.passwdmanager.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:39 org.schabi.newpipe.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:36 org.telegram.messenger.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:40 org.tvbrowser.tvbrowser.ab
-rw-r----- 1 mdomann mdomann    0 Dez 26 11:40 org.withouthat.acalendar.ab

any idea what i did wrong?

TIA Micha

**Comment by IzzySoft** [comment]
> or each attempt to backup an app i get a confirmation dialogue on the phone (which drives me crazy, can i give the permission one for all?)

No, that's not possible. If your device supports it (somehow some devices having trouble with that), you could however have *Adebar* doing the unlocking for you, using the AUTOCONFIRM feature. The Wiki gives some details on that.

> but all backed up files are zero bites big.

Nothing Adebar can do about that: it just creates the scripts with the ADB commands. Usually, 0 byte (or rather 41 byte) files indicate the corresponding app doesn't allow to be backed up (a dev can decide so). But I've never seen that for all apps on a device, mostly just a few. Could you please send me one of those backup scripts generated so I can check if something went wrong with its generation?

**Comment by Qrzy** [comment]
It also happens when versions of ADB on computer and the device don't match.

**Comment by IzzySoft** [comment]
@Qrzy Thanks for the pointer! Though I never had that either. If that's a frequent issue, I might need to make the location of the ADB binary configurable, so it can be defined per-device.

@Micha-Btz please include the ADB version as well then, and maybe try again with one matching your device. You should find it [here](https://android.izzysoft.de/downloads).

**Comment by Qrzy** [comment]
It's been quite long time since I used Adebar last time but I have faced exactly the same issue AFAIR. Adjusting ADB version helped me to go through.

**Comment by Micha-Btz** [comment]
I did a test with equal adb version and it worked. After that i tried the newest adb version on pc and it worked too. So it seems not a fault from adebar.
