### ISSUE TITLE
Partial restore to a tablet

### ISSUE THREAD

**Issue by silentnights** [IzzySoft/Adebar#27]
Hi,
I have issued a backup for a subset of applications from my phone, it is Oneplus One. I am trying to restore the partial backup into a tablet, Huawei Mediapad M2. Now when I start the restore script, I am getting the notification in the tablet that the restore will replace any data currently on the device. !
Does it mean it will wipe out all the data on the device? Or only the data relevant to the applications I am trying to restore?

Thanks in advance.

**Comment by IzzySoft** [comment]
That's not specific to *Adebar* but rather what `adb restore` does. What will be replaced depends on what your backup file contains. If it e.g. holds a single application backup (say `com.foobar` with `.apk` and data – which is what the scripts generated by *Adebar* would produce), it will only replace that app and its data. For multiple apps, simply sum it up (i.e. only the apps from the backups you decide to restore will be replaced).

I never restored a single-file complete-backup, so I cannot speak for that – but as you ask here, and I assume the backups you want to restore where created by a script *Adebar* generated, that doesn't matter in this context anyhow :stuck_out_tongue_winking_eye:

**Comment by silentnights** [comment]
Hi,
It appears that the backup did not go throw at first place. I realized that the files generated are empty. I am not getting any notification on the phone when I am supposed to confirm the backup.

But apparently the restore did not wipe out all my data in the target device. Which is a good thing. :-D

But do you know if there is anything I need to setup to make the backup work? The exit code from the backup device is zero, and it only generate empty files. :)

**Comment by IzzySoft** [comment]
Empty files (or files with a size of 41 bytes, which is the backup header) usually mean the corresponding apps are protected against backup (`ALLOW_BACKUP=FALSE`). But if you do not even receive a prompt on your device, that's strange.

Hard to say what that could be, without more details. What happens if you try running the backup command manually? Pick one of those apps, and run e.g. `adb backup -f com.example.ab -apk com.example` (if `com.example` is the package name of the app; you could grab those details from the backup script *Adebar* generated). Do you get prompted to confirm the backup? Is it then created correctly? Or are there any error messages, and what is the return code then?

**Comment by IzzySoft** [comment]
@silentnights Please check again with the latest *Adebar* code. Apparently Flashwalker had a comparable issue (empty/41-byte backup files) and found that, on his device, repeating the very same command solves it. I've just merged his PR, so you can give it a try.

**Comment by silentnights** [comment]
@IzzySoft Thanks for the update. Let me try it when I get home and will let you know the outcome. :)

**Comment by IzzySoft** [comment]
@silentnights how far is your way home? Did you arrive yet and had a chance to check? Is it safe to assume that, considering you didn't report back, your issue is solved? :wink:

**Comment by silentnights** [comment]
@IzzySoft Sorry I totally forgot about that.
I have tried with latest adebar and now it works. !

But I had a different problem. Even that I disabled all the apps except the one I was interested to backup, it still tried to backup all of them, and what worse is that I need to confirm each and everyone of them.

I did not continue the operation after couple of them, but at least I see there are some files created.

Do you like to close this issue as it is now resolved, and probably check the single app backup in a separate thread?

**Comment by IzzySoft** [comment]
Thought so :wink: But good to know it works now! :+1:

As for the "new points": Yes, Adebar doesn't check whether an app is (temporarily) disabled – it creates a script holding them all. While you still can edit that script *prior* to running it, it might not be a bad idea to at least have an option for that (something like `BACKUP_EXCLUDE_DISABLED`) so one can optionally have Adebar exclude them from the script created. Feel free to open a new issue on that!

For unlocking, there's an option `AUTO_CONFIRM`. There are some devices it doesn't seem to work with, and some where playing with `MK_AUTOCONFIRM_DELAY` might help. Not much I can do about that, sorry.

And yes, I'll now close this issue as your initial problem is solved. Be welcome opening a new issue for excluding disabled apps – but if your device doesn't support the auto-confirm, I wouldn't know how to deal with that.

**Comment by silentnights** [comment]
What is confusing me are those enable and disable files. I thought I can use them to pick the apps I want to backup. Is my understanding correct?

**Comment by IzzySoft** [comment]
No. And I thought the docu/wiki clarifies that. Those scripts cover the apps/components you've manually disabled – so in case of a factory-reset you can simply run the disable script to repeat those steps without the hazzle of doing it manually via GUI. The enable script is just the counterpart.
