### ISSUE TITLE
Not able to backup my un-rooted tablet's partitions

### ISSUE THREAD

**Issue by PhxCycler** [IzzySoft/Adebar#32]
I'm trying to backup all partitions on my un-rooted Dragon Touch V10 tablet (Android 7.0). As a test, I also tried to backup my rooted Moto G4 Play (Android 6.0.1). I was able to back up all the partitions on my Moto G4, so it seems as though I've successfully installed the Adebar program on my Windows 10 laptop. 

Here are some specifics: Tablet: Dragon Touch V10, Android 7.0, not rooted.

I've attached 3 files:
1) The partBackup script created by Adebar
2) An "ls -al" of the images directory after running the partBackup script on the V10
3) An "ls -al" of the images directory after running the corresponding partBackup script on my rooted Moto G4 Play

You can see from the ls listings that the Moto G4 did backup the partitions from the phone. You can also see that every partition backed up on the V10 are the same size. When I try to open any of them (with Peazip), I get an error stating that "Archive is not readable". I am able to open the archives from the Moto G4.

Do you have any idea why this is happening? Do I understand correctly that this was intended to run on devices which are not rooted?

Many thanks for your efforts and any feedback is welcomed.

[partBackup.txt](https://github.com/IzzySoft/Adebar/files/1462776/partBackup.txt)
[imagesDragonTouchV10.txt](https://github.com/IzzySoft/Adebar/files/1462777/imagesDragonTouchV10.txt)
[imagesMotoG4Play.txt](https://github.com/IzzySoft/Adebar/files/1462778/imagesMotoG4Play.txt)

**Comment by IzzySoft** [comment]
Very easy: You cannot backup partitions without root. Nothing Adebar can cure, sorry.
