### ISSUE TITLE
Restoring user apps and setting on different firmware?

### ISSUE THREAD

**Issue by danjde** [IzzySoft/Adebar#37]
I hope not to stress you :-)
I've made a userapp/setting backup on a original firmware Samsung Tab 4 from my Linux box.
Now I've installed LineageOS (matissewif) and try to restore apps and setting.
Running ./userrestore all seems works fine, on the tablet display I can see the starting and ending process. And the same on Linux terminal.
But at the end, if I look into the Android drawer I cannot see any **one** application!

Is it possible to restore user app from different firmware?

Many thanks again!

Davide

**Comment by IzzySoft** [comment]
I've done that multiple times in the past: between different Android versions (e.g. after updating the device), even across devices (phones as well as tablets), and never had an issue. That question also rather belongs to Google/AOSP, as Adebar is rather a wrapper around the `adb backup` and `adb restore` feature – so if there are compatibility issues, they are not due to Adebar, and there's nothing Adebar could do to "fix" them.

**Comment by danjde** [comment]
Ah, perhaps a bug on ADB
This is the restore log for a single ".ab" If it can be useful to you:

```
08-28 14:57:53.538   772  8169 I BackupManagerService: --- Performing full-dataset restore ---
08-28 14:57:53.553   772  8169 I BackupManagerService: Package stericson.busybox not installed; requiring apk in dataset
08-28 14:57:53.560   772  8169 D BackupManagerService: APK file; installing
08-28 14:57:53.560   772  8169 D BackupManagerService: Installing from backup: stericson.busybox
08-28 14:57:54.514   772  8169 E BackupManagerService: Unable to transcribe restored apk for install
08-28 14:57:54.514   772  8169 W BackupManagerService: io exception on restore socket read
08-28 14:57:54.514   772  8169 W BackupManagerService: java.io.EOFException: Unexpected end of ZLIB input stream
08-28 14:57:54.514   772  8169 W BackupManagerService: 	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:245)
08-28 14:57:54.514   772  8169 W BackupManagerService: 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
08-28 14:57:54.514   772  8169 W BackupManagerService: 	at com.android.server.backup.BackupManagerService$PerformAdbRestoreTask.readExactly(BackupManagerService.java:7730)
08-28 14:57:54.514   772  8169 W BackupManagerService: 	at com.android.server.backup.BackupManagerService$PerformAdbRestoreTask.skipTarPadding(BackupManagerService.java:7359)
08-28 14:57:54.514   772  8169 W BackupManagerService: 	at com.android.server.backup.BackupManagerService$PerformAdbRestoreTask.restoreOneFile(BackupManagerService.java:6906)
08-28 14:57:54.514   772  8169 W BackupManagerService: 	at com.android.server.backup.BackupManagerService$PerformAdbRestoreTask.run(BackupManagerService.java:6701)
08-28 14:57:54.514   772  8169 W BackupManagerService: 	at java.lang.Thread.run(Thread.java:761)
08-28 14:57:54.516   772  1598 I BackupManagerService: Full restore processing complete.
08-28 14:57:54.517   772  8169 D BackupManagerService: Full restore pass complete.

```

I've found [this page](https://lyubomyr-shaydariv.github.io/posts/2016-08-27-when-android-backup-and-restore-tools-may-fail/) where the author says:

> After a whole day of various experiments with another tools I've accidentally figured out that specifying the -apk key was the problem. Simply omitting the flag during a backup operation makes it fully restorable.

**Comment by IzzySoft** [comment]
> Ah, perhaps a bug on ADB

That's my assumption, yes.

> `java.io.EOFException: Unexpected end of ZLIB input stream`

That sounds like a broken backup, courtesy of the device's `adb backup` process. Bug report then should go to the "ROM baker".

> Simply omitting the flag during a backup operation makes it fully restorable.

Only if the app was installed beforehand. Otherwise, where should the app data be "assigned" to?

**Comment by IzzySoft** [comment]
Closing this as it looks like it's solved. We can reopen it again if my assumption was wrong.
