### ISSUE TITLE
stderr treated as app names

### ISSUE THREAD

**Issue by tukusejssirs** [IzzySoft/Adebar#4]
I just noticed that my disable file looks like [this](http://pastebin.com/U2g9Dj8M) – the error output is treated as stdout with the disabled apps. In my opinion you should work only with stdout not the whole terminal output. :)

More info on the error is [here](http://stackoverflow.com/a/23712546). :)

The stderr output is also visible in `$backup/sysbackup` file, too ([pastebin](http://pastebin.com/3MiLT6qm)),

And it also affects `$backup/sysrestore` ([pastebin](http://pastebin.com/4tFQJwsh)), `$backup/userbackup` ([pastebin](http://pastebin.com/Wthk8K6u)) and `$backup/userrestore` ([pastebin](http://pastebin.com/UXk4QCsw)) files.

**Comment by IzzySoft** [comment]
Thanks for pointing this out! I wonder why this doesn't happen here (I have Xposed installed as well on some devices). However: should be solved with 83c5286 (devel branch), could you please verify?

**Comment by tukusejssirs** [comment]
File `sysbackup` is exactly the same.

The output of of `$ adb shell pm list packages -3` is [here](http://pastebin.com/TEPJ43V8). I think `grep`-ing out only lines with `^package:` pattern would be a solution. (Or even piping the output to `sed '/^WARNING/d' -` would be the solution, too.)

**Comment by IzzySoft** [comment]
Are you sure you've pulled the latest code **_from the "devel" branch**_ and used that? I cannot find a single `pm list packages` in the code which doesn't end with `2>/dev/null` – so either those messages are not from STDERR, or you didn't update. Unfortunately I cannot test this myself, as none of the devices I have here show this behavior. If those messages are not from STDERR, I'd really have to check all places and "grep for `^package:", which I prefer to avoid if possible.

**Comment by tukusejssirs** [comment]
Well, I am sure. I tried even to run `adb shell pm list packages -3 2>/dev/null` in terminal on its own, but somehow the warnings are still there.

**Comment by IzzySoft** [comment]
Ah, OK – thanks for that detail; so those "warnings" are not printed to STDERR but to STDOUT. Then it seems we've got no other choice but filtering each returned line separately. I will see to that.

**Comment by IzzySoft** [comment]
Should be solved now with 2267b0f – could you please retry and confirm?

**Comment by tukusejssirs** [comment]
I confirm there are no warning now. Nice job! :)

**Comment by IzzySoft** [comment]
Thanks a lot! So I'm closing this now. Leaves the "some files not found" as only show-stopper for the pending v1.3.0 release – before I can go after your Dual-SIM support :)

Btw: last commit also solved the probably unwanted "progress output" for "Remove apps" :) To see those again, you've had to rise `PROGRESS` to at least level 4 now. I might even decide to push that up to level 5, as it's really just a "forgotten debug message" (I've never encountered any app in that section, and so left it out of curiosity)
