### ISSUE TITLE
More a question than a bug, but why care about "adb backup"

### ISSUE THREAD

**Issue by taliesin** [IzzySoft/Adebar#44]
Looking into the ab files generated wouldn't it be so much easier to simply copy/rsync/tar/whatever 

* /data/data
* /data/app
* /system/app
* even /etc

at least for rooted devices ...
This would even work over the network (ssh) without ever touching adb ...
Probably I'm missing something here ..., probably you are targeting non-rooted devices?

**Comment by IzzySoft** [comment]
No, it wouldn't even be possible on devices which are not rooted. Furthermore, it would involve caring for permissions and ownership. And third, you'd need to address this to the AOSP team: it's `adb backup` creating the `.ab` files, not Adebar :wink:

As for targeting: I target both. Wherever possible, non-rooted devices should be supported.

**Comment by taliesin** [comment]
Yes for non-rooted devices you have no choice, but I think there are some drawbacks on rooted devices:
- you depend on the allowance of applications to make a backup
- you can't backup system settings (/etc)
- without auto confirmation it's a pain in the a**, with auto confirmation it's fully device dependent (and probably still takes like forever), but I didn't try ...
- you'll probably have inconsistent state if the file system is mounted during backup (it might be safe if adb backup does some magic here).
- you need to connect the device via USB

Of course for none of the above Adebar is to be held liable, it's simply the adb backup method.

As far as permissions are concerned using something like rsync or tar will store user and group ids along with file permissions, so there shouldn't be any problem. Taking backups to different devices will probably generate issues.

I'm currently looking into the backup topic and I think I'll implement my backup using ssh and rsync (on a rooted device). 
To avoid inconsistent data one could use TWRP recovery scripts (write a script to backup data, start into recovery and back to the system from there, send the local backup data to somewhere safe (via scp et al.)).
I was actually wondering if there was something in a .ab file that is outside the directories in my original question, looking into the files Adebar got from my device it does not seem so.

Again definitely NOT a flaw in Adebar!

**Comment by IzzySoft** [comment]
* on rooted devices, you can force all apps to allow backup (e.g. with the corresponding Xposed module
* if you want to backup `/etc`, you can do that by other means – after all, it's just a recursive copy
* what do you mean by "without auto-confirmation"? If your device doesn't support that (huh?) there's nothing Adebar can do about it (Adebar supports auto-confirm)
* no inconsistent state with ADB backups (why?)
* sure you need the device connected. That's how Adebar (and `adb backup`) works

I won't implement that in Adebar. And sorry, I also lack the time to discuss that in detail…
