### ISSUE TITLE
Moving to Codeberg

### ISSUE THREAD

**Issue by IzzySoft** [IzzySoft/Adebar#46]
All my other Github projects already have been migrated – now it's time to move Adebar to Codeberg as well. To have your contributions properly attributed/mapped to you: would you mind creating an account there (unless you already have done that)? I'll wait a few weeks to give you a chance (considering some of you might be on vacation, or want some time to consider first) before I initiate the move.

@inktrap @d5ve @Flashwalker @JimboJoe @Qrzy @n0tnull @chaotix- @Catfriend1

Looking forward to see you there! And should you have chosen a different username at Codeberg, please let me know so I can arrange a mapping.

PS: Same applies to anyone having participated in issues 😉 Apologies if I missed someone – I just noticed the "Insights › Contributors" list seems to be incomplete…

**Comment by ghost** [comment]
Hi,

Thanks for the info. Maybe I'll register sometime very later to the new place. But thanks for taking care precisely. It's no drama for me if my name gets somehow lost on commits, just take the code :-).

**Comment by d5ve** [comment]
I just set up https://codeberg.org/d5ve cheers.

**Comment by IzzySoft** [comment]
@Catfriend1 it won't get lost on commits (as the commit usually carries name and email of the committer), but have no nick associated. But your comments in issues won't be mapped.

@d5ve cool, thanks! I'll still wait a little – for the others, and for the next Gitea release (which is expected to have some migration improvements – though migration already goes pretty smooth, including issues, PRs, wiki and all that).

**Comment by JimboJoe** [comment]
Account created at https://codeberg.org/JimboJoe.
Thanks for your initiative :wink:

**Comment by inktrap** [comment]
https://codeberg.org/inktrap
:)

**Comment by IzzySoft** [comment]
Yay! Nearing completion :smiley:

**Comment by IzzySoft** [comment]
Okay, if anyone decides later, let me now then "[over there](https://codeberg.org/izzy/Adebar/issues/46)" :smiley: Just waiting for the mirror structure to be setup now, and then I'll close the door here (archive this repo). It will then be "fed" on each release, but otherwise be read-only.

Thanks again to all of you for your contributions! I'm looking forward to see some more at Codeberg then, whenever it fits. I'll close this issue when all is complete, most likely within the next days.

**Comment by IzzySoft** [comment]
Move completed! Thankks again to all! This issue will now be closed, and the repo archived in a few minutes. Please check if you're mapped correctly on Codeberg; the issue over there is still open for you to report if there are issues.
