### ISSUE TITLE
Add support to extract Helium backups

### ISSUE THREAD

**Issue by superbonaci** [IzzySoft/Adebar#48]
Request: ability to extract adb backups:
helium-backup.ab  > simple.tar > view/explore/extract all files
helium-backup.ab  > simple.tar > convert to android adb backup

**Comment by IzzySoft** [comment]
Please take a look into the `tools/` directory: [ab2tar](https://github.com/IzzySoft/Adebar/blob/master/tools/ab2tar) is available there for quite a while already. `ab2tar helium-backup.ab` gives you your tar file.

No idea about the opposite direction. But if you know a way proven to work, tell me and I'll take a look.

**Comment by IzzySoft** [comment]
> helium-backup.ab > simple.tar > convert to android adb backup

Here you can skip the last 2 steps. Helium is just an on-device front-end to ADB backup, so you e.g. can restore a Helium backup via `adb restore` directly.

As your two items are thus solved, I'm closing this issue. Feel free to ping me should I have missed something.
