### ISSUE TITLE
Dual-SIM: Support provider-info for second SIM

### ISSUE THREAD

**Issue by tukusejssirs** [IzzySoft/Adebar#5]
Accidently, I made a test backup while the sim card was not unlocked. The `provider info` in `$backup_dir/docs/deviceInfo.md` file was the following:

```
### Provider info
* Mobile provider: Orange
* Provider country: sk
* Provider code: 23101
* SIM state: PIN_REQUIRED
```

which is not true. The following is accurate `provider info` _after_ the sim card was unlocked:

```
### Provider info
* Mobile provider: O2
* Provider country: sk
* Provider code: 23106
* SIM state: READY
```

**Comment by IzzySoft** [comment]
I'm not sure what I should do here – I'd say "works as designed". Whether details might be incorrect can be told by `SIM state`. _Adebar_ should not prompt for any input, so something like "please unlock SIM for correct information" is no option here. Obviously, correct/trustable information can only be obtained with the SIM unlocked – which I'm afraid is nothing _Adebar_ should deal with (if it's even possible to unlock the SIM via ADB).

What did you want to suggest here? Of course I'm open to ideas – though I don't promise to pick them :)

**Comment by tukusejssirs** [comment]
Sorry that I have not stated it clearer. I think it would be nice first to check (1) if the sim card is inserted, (2) then if it is unlocked and (3) finally display the `provider info` accordingly – `sim card not present` or `sim card not unlocked` or (if the conditions are met) it should get all the usual information.

Well, my phone’s actually a dual sim phone, so probably we could tweak it to check if it’s a dual phone and if yes, we could get the info of the other sim card, too. [Here](http://pastebin.com/xQAzX82q)’s my `adb shell getprop|grep gsm` output – it might be of some help. ([reference](http://stackoverflow.com/questions/20934274/detect-the-current-primary-sim-in-dual-sim-mobile))

**Comment by IzzySoft** [comment]
For the first part: rather not. The SIM card state is included, so why should the other details be suppressed? While this might fit for you, others might complain then otherwise. And I'm not sure if we really want another config setting for that.

Concerning dual-sim: That's a different matter. Are you saying currently it shows only one SIM in _Adebar's_ generated docs? Ah, yes, I see.

Are you agreeing we change this issue to "Dual-SIM: Support provider-info for second SIM" (dropping the first part)? Thanks to your `adb shell getprop|grep gsm`, that shouldn't be too hard to do – though I'd postpone it after the v1.3.0 release (due as soon we've solved the other open issues).

**Comment by tukusejssirs** [comment]
Okay then, let’s drop the first part, though in the future, I would like to implement some accepted parameters to `./adebar` to choose what should be backed up and what info should be collected (one could choose `config` file/directory or provide the info using parameters), but for now it does not really matter to me. :)

As for dual sim, yes, only for one sim there’s info.

Okay, no problem with postponing it. Can I ask you a rather stupid question? Where is the <i>version number</i>, e.g., in adebar? How could determine what version a `git pull` is? Thank you. :)

**Comment by IzzySoft** [comment]
Time to test – another `git pull` on the devel branch :) Please let me know if it works as expected, as I cannot test it (have no dual-SIM device).

**Comment by tukusejssirs** [comment]
Perfect! Working just as expected. Well Done! :)

**Comment by IzzySoft** [comment]
Yeeha! :innocent: Thanks again. So I'll merge the latest changes to the master branch then.

Don't get me wrong when I write I hope you find some more "issues" – nice working with you! Be welcome anytime with more interesting feature requests. The last 2 days we got more done on _Adebar_ than I did in the 2 month before ;)
