### ISSUE TITLE
Oops in pkg at line 229: Unexpected: '    mtkFlags=[ ]'

### ISSUE THREAD

**Issue by tukusejssirs** [IzzySoft/Adebar#6]
I don’t know if it might help you, but I modified line 232 in ./adebar-cli to

```
local txt="Oops in $1 at line $2: $3 ... level = $level"
```

so the output looks like

```
Oops in pkg at line 229: Unexpected: '    mtkFlags=[ ]' ... level = 2
```

**Comment by IzzySoft** [comment]
To investigate this, I'd need some context. Could you please provide the output of

```
adb shell "dumpsys package" |egrep -A99999 "^Packages:" |egrep -B99999 "^Shared users:"
```

This will create quite a lot of output, so you best redirect it into a file and then either pastebin it, or zip/tar.gz & attach it. Thanks!

**Comment by tukusejssirs** [comment]
Here’s the [output](http://pastebin.com/gApZ6Kbq).

**Comment by IzzySoft** [comment]
Thanks. Browsing through that, I see in most cases this gives no additional details. The few places I've found different:

```
mtkFlags=[ OPERATOR ]
```

15 times in your pretty long list. I'm undecided whether I should integrate that with the generated docs (as it's 1) specific to MTK devices only and 2) not clear to me whether it's important at all) – or just make sure it doesn't throw an "Oops". Couldn't find any info on those, either.

These are your apps carrying that `OPERATOR` flag: `com.gameloft.android.GloftRF14`, `com.accuweather.android`, `com.facebook.katana`, `com.gameloft.android.GloftGF2H`, `com.gamestore`, `com.mediatek.FMRadio`, `com.UCMobile.intl`, `com.evernote`, `com.route66.maps5`, `com.gameloft.android.gdc`, `com.guvera.android`, `com.twitter.android`, `com.skype.raider`, `com.gameloft.android.HEP.GloftA7HP`, `com.txtr.android.lenovo`. Does that give you any clue? I doubt the apps themselves shipped with specific "MTKFlags", though that might be – but could it be some "special settings" you've applied with MTK specific things?

**Comment by IzzySoft** [comment]
So what. `git pull` the devel branch again and see – then let me know if it works correctly (remember, I cannot test this as I have no MTK device).

**Comment by tukusejssirs** [comment]
Well, most of those apps (if not all – I just don’t know what some of these apps are) are definitely bloatware, probably installed by `OPERATOR`. So I don’t think there’s no need to integrate to the docs.

> I doubt the apps themselves shipped with specific "MTKFlags"

I haven’t modified any flags, so I’m quite sure that the manifacturer (Lenovo) did it. :)

> could it be some "special settings" you've applied with MTK specific things?

I haven’t got a clue. Probably not. :)

**Comment by tukusejssirs** [comment]
I pulled the devel branch and the `oops` warning’s still there (a bit different):

```
Oops in pkg at line 236: Unexpected: '    usesOptionalLibraries:'
```

And I have no problem with testing your script – I’m even glad I can help you. :)

**Comment by IzzySoft** [comment]
Thanks a lot! I don't think I want to evaluate those details currently (`usesOptionalLibraries`). Could you please try: Edit `lib/packagedata.lib`, line 106, add `usesOptionalLibraries` to the `P_SKIP` array, and then run _Adebar_ again to see whether this "Oops" is gone? Most likely this will bring up another "Ooops" on `usesLibraryFiles`, so do the same with that one. Then let me know.

We might collect a few more "Oopses" this way – but let's decide which ones we want to skip and which to use when our collection is complete :)

**Comment by tukusejssirs** [comment]
I did what you said, but `Oops in pkg at line 236: Unexpected: '    usesOptionalLibraries:'` still in the output.

Here’s the modified line 106 of `lib/packagedata.lib`:

``` bash
local P_SKIP=(userId sharedUser pkg resourcePath nativeLibraryPath versionCode targetSdk timeStamp signatures permissionsFixed pkgFlags applicationInfo usesOptionalLibraries)
```

**Comment by IzzySoft** [comment]
Ah, my bad – cannot work this way: it uses a colon (`:`) as separator, not a `=`. OK, different approach – please `git pull` again the devel branch.

**Comment by tukusejssirs** [comment]
Here you go. Now the output is clean. :)

``` bash
        # we skip some details here. Later we might decide to integrate them.
        in_array $tmpstring "${P_SKIP[@]}" && continue
        [[ "$zeile" = "    grantedPermissions:" ]] && continue
        [[ "$zeile" = "    usesOptionalLibraries:" ]] && continue
        [[ "$zeile" = "    usesLibraryFiles:" ]] && continue
        [[ "$zeile" = "    usesLibraries:" ]] && continue
        [[ "$zeile" = "    libraries:" ]] && continue
        [[ "${zeile:0:6}" = "      " ]] && continue
        [[ -z "${zeile%%* }" ]] && break # end of package list is an empty line, sometimes with spaces
```

**Comment by IzzySoft** [comment]
Wow – thanks a lot! Easy for me this time (just copy-pasta), another commit – and this issue can be closed :+1: 

As the comment indicates, we might use those details later, introducing a "common" config keyword to make that optional (currently, something like "IncludePkgLibraryDetails" seems fitting – except for the permissions), but not now :)
