### ISSUE TITLE
Editing comments in `doc/config.sample` to be more understandable

### ISSUE THREAD

**Issue by tukusejssirs** [IzzySoft/Adebar#8]
Some of the comments are somewhat misleading or ambigious (in my opinion). I’d like to change the wording and if you approve it, it would be nice to merge it.

Could I ask you for contributor ’privilege'? So I could create separate branch to commit my changes and after you reviewed my changes, you could just simply merge it to the master. ;)

**Comment by IzzySoft** [comment]
You can fork the project (see the big "Fork" button in the upper-right of the web page?), create your branch there, and then send in pull requests – that's how Github works for this. Of course I gladly see your contributions here – they already proved useful in the past, when I copy-pasted them :)

As for comments in the sample config: they are intentionally kept _short_ (ambiguity, if there, of course is _not_ intentional) – verbose descriptions belong to the wiki.

**Comment by tukusejssirs** [comment]
Okay, I forked `adebar`. You know, I’m quite new to `git` and github, I just don’t everything how to use (though I know about them xD).

As for the `config` file comments, neither do I want the comments in full length, but still I think they should be a bit more accurate. :)

**Comment by IzzySoft** [comment]
That's fine – then we both are "talking the same language". As you're a starter with Git/Github, you might find my "[starter's link collection](https://gist.github.com/IzzySoft/85627ffcb1ac4b24c9b1)" useful ;)

**Comment by tukusejssirs** [comment]
Thank you, that’s very nice of you. :)

**Comment by IzzySoft** [comment]
Is this still an issue? No update for almost 3 years, so I tend to close it.

**Comment by tukusejssirs** [comment]
Well, I have long forgotten about this issue. I checked the file if it has changed the wording (in comments), but it is (more or less) the same. And as I have not used `adebar` recently, I cannot suggest any changes.

So the question if the issue should be closed, is that do as you wish. :) ... Probably yes, for I can't propose any suggestion. Sorry.

**Comment by IzzySoft** [comment]
Thanks for coming back to it, @tukusejssirs! As you have no specific suggestions at the moment, and neither have I, I think I'll close it for now. Feel free to use it again whenever you come up with specifics, and we can reopen it any time.
